# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnrampProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnrampProject
  pod 'SDWebImage', '~> 5.0'

  target 'OnrampProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnrampProjectUITests' do
    # Pods for testing
  end

end
